sudo: false
language: ruby
rvm:
- 2.5.1
- ruby-head
# gemfile: "gems.rb"
before_install: gem install bundler --no-document # Fixes ruby 2.5.1 tests
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database awsrails_test;' -U postgres
matrix:
  allow_failures:
  - rvm: ruby-head
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: us-east-1
  app: aws-continuous-deployment-test-1
  env: aws-rails
  bucket_name: elasticbeanstalk-us-east-1-910353042999
  on:
    repo: sleepepi/aws-rails
    branch: master
